# These are supported funding model platforms

github: [jinosabu1999]
patreon: jinosabu1999
ko_fi: jinosabu1999
buy_me_a_coffee: jinosabu1999
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
